/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Interface.pfAdmin;

import com.Business.Ecosys.EcoSystem;
import com.Business.advertisement.AdvertisementList;
import com.Business.database.DB4OUtil;
import com.Business.enterprise.Enterprise;
import com.Business.streamer.StreamerList;
import com.Business.user.User;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author yangyuxuan
 */
public class PfAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form PfAdminWorkArea
     */
    JPanel rightPanel;
    private AdvertisementList advertisements;
    private StreamerList streamers;
    DB4OUtil db4o;
    User user;
    Enterprise enterprise;
    private EcoSystem ecosystem;
    public PfAdminWorkArea(JPanel rightPanel, DB4OUtil db4o, User user, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        this.rightPanel = rightPanel;
        this.user = user;
        this.db4o = db4o;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        checkAdsBtn = new javax.swing.JButton();
        checkStrFbBtn = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        mngStreamerBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 24)); // NOI18N
        jLabel1.setText("Platform Admin Work Area");

        checkAdsBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        checkAdsBtn.setText("Check Submitted Advertisement");
        checkAdsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAdsBtnActionPerformed(evt);
            }
        });

        checkStrFbBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        checkStrFbBtn.setText("Check Streamer Feedback");
        checkStrFbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkStrFbBtnActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jButton4.setText("Change Password");

        mngStreamerBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        mngStreamerBtn.setText("Manage Streamers");
        mngStreamerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngStreamerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkStrFbBtn)
                    .addComponent(checkAdsBtn)
                    .addComponent(mngStreamerBtn)
                    .addComponent(jButton4)
                    .addComponent(jLabel1))
                .addGap(352, 352, 352))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addComponent(checkAdsBtn)
                .addGap(36, 36, 36)
                .addComponent(checkStrFbBtn)
                .addGap(32, 32, 32)
                .addComponent(mngStreamerBtn)
                .addGap(35, 35, 35)
                .addComponent(jButton4)
                .addContainerGap(245, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkAdsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAdsBtnActionPerformed
        // TODO add your handling code here:
        CheckAdvertisementJPanel jPanel = new CheckAdvertisementJPanel(rightPanel, db4o, user, enterprise, ecosystem);
        rightPanel.add("CheckAdvertisementJPanel", jPanel);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_checkAdsBtnActionPerformed

    private void checkStrFbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkStrFbBtnActionPerformed
        // TODO add your handling code here:
        CheckStreamerFeedbackJPanel jPanel = new CheckStreamerFeedbackJPanel(rightPanel, db4o, user, enterprise, ecosystem);
        rightPanel.add("CheckStreamerFeedbackJPanel", jPanel);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_checkStrFbBtnActionPerformed

    private void mngStreamerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngStreamerBtnActionPerformed
        // TODO add your handling code here:
        ManageStreamerJPanel jPanel = new ManageStreamerJPanel(rightPanel,db4o,user,enterprise,ecosystem);
        rightPanel.add("ManageStreamerJPanel", jPanel);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_mngStreamerBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkAdsBtn;
    private javax.swing.JButton checkStrFbBtn;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mngStreamerBtn;
    // End of variables declaration//GEN-END:variables
}
