/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Interface.adAdmin;

import com.Business.Ecosys.EcoSystem;
import com.Business.advertisement.AdvertisementList;
import com.Business.database.DB4OUtil;
import com.Business.enterprise.Enterprise;
import com.Business.sponsor.Sponsor;
import com.Business.streamer.StreamerList;
import com.Business.user.User;
import com.Interface.adAdmin.CheckSubAdvertisementJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author yangyuxuan
 */
public class AdAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdAdminWorkAreaJPanel
     */
    private JPanel rightPanel;
    private DB4OUtil db4o;
    private User user;
    private Enterprise enterprise;
    private EcoSystem ecosystem;
    public AdAdminWorkAreaJPanel(JPanel rightPanel, DB4OUtil db4o, User user, Enterprise enterprise, EcoSystem ecosystem) {
        this.rightPanel = rightPanel;
        this.db4o = db4o;
        this.user = user;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        //this.advertisements = advertisements;
        initComponents();
        GenerateName();
    }
    
    public void GenerateName(){
        usernameJL.setText(user.getUserName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CheckStrFbBtn = new javax.swing.JButton();
        checkSubAdBtn = new javax.swing.JButton();
        mngspoBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        usernameJL = new javax.swing.JLabel();
        tip1 = new javax.swing.JLabel();
        Tip2 = new javax.swing.JLabel();
        tip3 = new javax.swing.JLabel();
        tip4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jLabel1.setText("Advertisement Admin Work Area");

        CheckStrFbBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        CheckStrFbBtn.setText("Final Advertisement Control Audit");
        CheckStrFbBtn.setToolTipText("");
        CheckStrFbBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CheckStrFbBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hideTip(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                showTip(evt);
            }
        });
        CheckStrFbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckStrFbBtnActionPerformed(evt);
            }
        });

        checkSubAdBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        checkSubAdBtn.setText("Check Submitted Advertisements");
        checkSubAdBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                checkSubAdBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                checkSubAdBtnMouseEntered(evt);
            }
        });
        checkSubAdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSubAdBtnActionPerformed(evt);
            }
        });

        mngspoBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        mngspoBtn.setText("Manage sponsor");
        mngspoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mngspoBtnMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mngspoBtnMouseEntered(evt);
            }
        });
        mngspoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngspoBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Welcome back, ");

        usernameJL.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        usernameJL.setText("jLabel3");

        jButton1.setText("Check Completed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameJL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tip1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tip2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tip4, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mngspoBtn)
                            .addComponent(CheckStrFbBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tip3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(checkSubAdBtn)))
                .addGap(342, 342, 342))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameJL))
                .addGap(137, 137, 137)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(checkSubAdBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tip2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(CheckStrFbBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tip1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mngspoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tip3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tip4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkSubAdBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSubAdBtnActionPerformed
        // TODO add your handling code here:
        CheckSubAdvertisementJPanel jPanel = new CheckSubAdvertisementJPanel(rightPanel, db4o, user, enterprise, ecosystem);
        rightPanel.add("CheckSubAdvertisementJPanel", jPanel);
        CardLayout layout= (CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_checkSubAdBtnActionPerformed

    private void CheckStrFbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckStrFbBtnActionPerformed
        // TODO add your handling code here:
        CheckStreamerFeedbackJPanel jPanel = new CheckStreamerFeedbackJPanel(rightPanel, db4o, user, enterprise,ecosystem);
        rightPanel.add("CheckStreamerFeedbackJPanel", jPanel);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_CheckStrFbBtnActionPerformed

    private void mngspoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngspoBtnActionPerformed
        // TODO add your handling code here:
        ManageSponsorJPanel jPanel = new ManageSponsorJPanel(rightPanel, db4o, user, enterprise, ecosystem);
        rightPanel.add("ManageSponsorJPanel", jPanel);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_mngspoBtnActionPerformed

    private void showTip(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showTip
        // TODO add your handling code here:
        tip1.setText("you can check the advertisement of which stream accept");
    }//GEN-LAST:event_showTip

    private void hideTip(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideTip
        // TODO add your handling code here:
        tip1.setText("");
    }//GEN-LAST:event_hideTip

    private void checkSubAdBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkSubAdBtnMouseEntered
        // TODO add your handling code here:
        Tip2.setText("Agree or reject the Advertisement apply");
    }//GEN-LAST:event_checkSubAdBtnMouseEntered

    private void checkSubAdBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkSubAdBtnMouseExited
        // TODO add your handling code here:
        Tip2.setText("");
    }//GEN-LAST:event_checkSubAdBtnMouseExited

    private void mngspoBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mngspoBtnMouseEntered
        // TODO add your handling code here:
        tip3.setText("Create or delet a sponsor account");
    }//GEN-LAST:event_mngspoBtnMouseEntered

    private void mngspoBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mngspoBtnMouseExited
        // TODO add your handling code here:
        tip3.setText("");
    }//GEN-LAST:event_mngspoBtnMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CheckAllRequestJPanel jPanel = new CheckAllRequestJPanel(rightPanel, db4o, user, enterprise);
        rightPanel.add("CheckAllRequestJPanel", jPanel);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckStrFbBtn;
    private javax.swing.JLabel Tip2;
    private javax.swing.JButton checkSubAdBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton mngspoBtn;
    private javax.swing.JLabel tip1;
    private javax.swing.JLabel tip3;
    private javax.swing.JLabel tip4;
    private javax.swing.JLabel usernameJL;
    // End of variables declaration//GEN-END:variables
}
