/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Interface.sponser;

import com.Business.Ecosys.EcoSystem;
import com.Business.Network.Network;
import com.Business.advertisement.Advertisement;
import com.Business.advertisement.AdvertisementList;
import com.Business.database.DB4OUtil;
import com.Business.enterprise.Enterprise;
import com.Business.sponsor.Sponsor;
import com.Business.user.User;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yangyuxuan
 */
public class ManageAdvertisementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAdvertisementJPanel
     */
    private JPanel rightPanel;
    private Sponsor sponsor;
    DB4OUtil db4o;
    User user;
    EcoSystem ecosystem;
    Enterprise enterprise;
    public ManageAdvertisementJPanel(JPanel rightPanel, DB4OUtil db4o, User user, EcoSystem ecosystem, Enterprise enterprise) {
        initComponents();
        this.rightPanel = rightPanel;
        this.sponsor = sponsor;
        this.db4o = db4o;
        this.user = user;
        this.ecosystem = ecosystem;
        this.enterprise = enterprise;
        populateTable();
    }
    
    public void populateTable(){
        int rowCount = manageAdTbl.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)manageAdTbl.getModel();
        for(int i = rowCount - 1; i >=0; i--) {
            dtm.removeRow(i);
        }
        
        for(Advertisement ad : user.getAdvertisementList().getAdertisements()){
            Object row[] = new Object[dtm.getColumnCount()];
            
            row[0] = ad;
            row[1] = ad.getForm().getTitle();
            row[2] = ad.getStatus();
            //row[3] = p.getEnterpriseList().getEnterpriseList().size();
            dtm.addRow(row);
        }
        
        sponsorAdminCB.removeAllItems();

                for(User u: enterprise.getUserList().getUserList()){
                    if(u.getRole().getRoleType().getValue().equals("Advertisement Admin Role")){
                    sponsorAdminCB.addItem(u);
                    }
                }
            }
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        manageAdTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        sponsorAdminCB = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        manageAdTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Title", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageAdTbl);
        if (manageAdTbl.getColumnModel().getColumnCount() > 0) {
            manageAdTbl.getColumnModel().getColumn(0).setResizable(false);
            manageAdTbl.getColumnModel().getColumn(1).setResizable(false);
            manageAdTbl.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        jLabel1.setText("Management Advertisements");

        deleteBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        deleteBtn.setText("Delete");

        backBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        backBtn.setText("<<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        submitBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        viewBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        viewBtn.setText("View Detail");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        sponsorAdminCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        sponsorAdminCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sponsorAdminCBActionPerformed(evt);
            }
        });

        jLabel8.setText("Sponsor admin:");

        jButton1.setText("hit me!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sponsorAdminCB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submitBtn, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewBtn)
                        .addGap(85, 85, 85)))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(sponsorAdminCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(submitBtn)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBtn)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewBtn)
                    .addComponent(backBtn))
                .addContainerGap(232, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = manageAdTbl.getSelectedRow();
        Advertisement ad = (Advertisement)manageAdTbl.getValueAt(selectedRow, 0);
        if(selectedRow < 0){ 
            JOptionPane.showMessageDialog(null, "Please select a row before you submit");
        }else if(ad.getStatus().equals("Waiting for submit")){
            ad.setStatus("adAdmin checking");
            User adAdmin = (User)sponsorAdminCB.getSelectedItem();
            ad.setAdvertisementAdmin(adAdmin);
            adAdmin.getAdvertisementList().getAdertisements().add(ad);

            db4o.storeSystem(ecosystem);
            JOptionPane.showMessageDialog(null,"The apply successfully submitted to admin");
            populateTable();
        }else if(ad.getStatus().equals("adAdmin checking")|| ad.getStatus().equals("Advertisement Updated")){
            JOptionPane.showMessageDialog(null, "you already submitted");
        }else{
            JOptionPane.showMessageDialog(null, "you can not do that", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        populateTable();
    }//GEN-LAST:event_submitBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        try {
            // TODO add your handling code here:
            int selectedRow = manageAdTbl.getSelectedRow();
            
            if(selectedRow < 0){
                JOptionPane.showMessageDialog(null, "Please select a row before you check the detail");
            }
            Advertisement ad = (Advertisement)manageAdTbl.getValueAt(selectedRow, 0);
            ViewAdvertisementJPanel jPanel = new ViewAdvertisementJPanel(rightPanel, ad, ecosystem, db4o);
            rightPanel.add("ViewAdvertisementJPanel", jPanel);
            CardLayout layout = (CardLayout)rightPanel.getLayout();
            layout.next(rightPanel);
        } catch (IOException ex) {
            Logger.getLogger(ManageAdvertisementJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void sponsorAdminCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sponsorAdminCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sponsorAdminCBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable manageAdTbl;
    private javax.swing.JComboBox sponsorAdminCB;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
