/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Interface.streamer;

import com.Business.Ecosys.EcoSystem;
import com.Business.advertisement.Advertisement;
import com.Business.database.DB4OUtil;
import com.Business.enterprise.Enterprise;
import com.Business.user.User;
import com.Interface.pfAdmin.ViewAdvertisementDetailJPanel;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yangyuxuan
 */
public class ViewAvaAdvertisements extends javax.swing.JPanel {

    /**
     * Creates new form ViewAvaAdvertisements
     */
    private DB4OUtil db4o;
    private JPanel rightPanel;
    private User user;
    private Enterprise enterprise;
    private Advertisement ad;
    private EcoSystem ecosystem;
    
    public ViewAvaAdvertisements(JPanel rightPanel, DB4OUtil db4o, User user, Advertisement ad, EcoSystem ecosystem) {
        initComponents();
        this.rightPanel = rightPanel;
        this.enterprise = enterprise;
        this.user = user;
        this.db4o = db4o;
        this.ad = ad;
        this.ecosystem = ecosystem;
        populateTable2();
    //    System.out.println(user.getPassword() );
    }

 

    public void populateTable2(){
        int rowCount = submittedADTbl.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)submittedADTbl.getModel();
        for(int i = rowCount - 1; i >=0; i--) {
            dtm.removeRow(i);
        }   
        //广告还没筛选  
    
        for(User u: user.getEnterprise().getUserList().getUserList()){
            if(u.getRole().getRoleType().getValue().equals("Platform Admin Role")){
       // System.out.println( user.getEnterprise().getName()+"???");
                for(Advertisement ad: u.getAdvertisementList().getAdertisements()){
                    if(ad.getStatus().equals("Waiting for apply")){
                    Object row[] = new Object[dtm.getColumnCount()];
                    row[0] = ad;
                    row[1] = ad.getForm().getTitle();
                    row[2] = (ad.getForm().getFunds())*0.5;
                    row[3] = ad.getSubmitDate();
     //               row[3] = ad.getForm().getAdvertisementComment();
                    dtm.addRow(row);
                    }
                }
             }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        submittedADTbl = new javax.swing.JTable();
        viewDetailBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        submittedADTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Rewards", "Create Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(submittedADTbl);

        viewDetailBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        viewDetailBtn.setText("View Detail");
        viewDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        jLabel2.setText("Avaliable Advertisements ");

        backBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        backBtn.setText("<<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jButton1.setText("hit me!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(backBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewDetailBtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(502, 502, 502)
                            .addComponent(jButton1))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn)
                    .addComponent(viewDetailBtn))
                .addContainerGap(258, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailBtnActionPerformed
        try {
            // TODO add your handling code here:
            int selectedRow = submittedADTbl.getSelectedRow();
            
            if(selectedRow < 0){
                JOptionPane.showMessageDialog(null, "Please select a row before you check the detail");
            }
            Advertisement ad = (Advertisement)submittedADTbl.getValueAt(selectedRow, 0);
            
            ViewAdvertisementDetail jPanel = new ViewAdvertisementDetail(rightPanel, db4o, user, ad, ecosystem);
            rightPanel.add("ViewAdvertisementDetail", jPanel);
            CardLayout layout = (CardLayout)rightPanel.getLayout();
            layout.next(rightPanel);
        }
         catch (IOException ex) {
            Logger.getLogger(ViewAvaAdvertisements.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_viewDetailBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        populateTable2();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable submittedADTbl;
    private javax.swing.JButton viewDetailBtn;
    // End of variables declaration//GEN-END:variables
}
