/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.Interface;

import com.Business.Ecosys.EcoSystem;
import com.Business.Network.Network;
import com.Business.database.DB4OUtil;
import com.Business.enterprise.Enterprise;
import com.Business.organization.Organization;
import com.Business.user.User;
import com.Business.user.UserList;
import com.Interface.adAdmin.AdAdminWorkAreaJPanel;
import com.Interface.admin.AdminWorkArea;
import com.Interface.pfAdmin.PfAdminWorkArea;

import java.awt.CardLayout;
import com.Interface.sponser.CreateAdvertisementJPanel;
import com.Interface.sponser.SponsorWorkAreaJPanel;
import com.Interface.streamer.StreamerWorkArea;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rachelwang
 */
public class LoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginJPanel
     */
    
    JPanel rightPanel;
    EcoSystem ecosystem;
    DB4OUtil db4o;
    public LoginJPanel(JPanel rightPanel, EcoSystem ecosystem, DB4OUtil db4o) {
        initComponents();
        this.rightPanel = rightPanel;
        this.ecosystem = ecosystem;
        this.db4o = db4o;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        signupBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        passwordTF = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to <TimTeamTim> ");

        jLabel2.setText("UserName: ");

        jLabel3.setText("Password:");

        usernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTFActionPerformed(evt);
            }
        });

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        signupBtn.setText("Sign Up");
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Don't have an account?");

        passwordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jLabel5.setText("advertisement managemet platform");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jLabel1))
                        .addComponent(jLabel5)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signupBtn)
                .addGap(260, 260, 260))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(loginBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signupBtn)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTFActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String username = usernameTF.getText();
        char[] passwordCharArray = passwordTF.getPassword();
        String password = String.valueOf(passwordCharArray);
        UserList userList = new UserList();
        for(User u: ecosystem.getUserList().getUserList()){
            userList.getUserList().add(u);
        }
        
        for(Network n: ecosystem.getNetworkList().getNetworkList()){
            for(Enterprise e: n.getEnterpriseList().getEnterpriseList()){
                for(User u: e.getUserList().getUserList()){
                    userList.getUserList().add(u);
                }
            }
        }
//        for(Network n: ecosystem.getNetworkList().getNetworkList()){
//            for(Enterprise e: n.getEnterpriseList().getEnterpriseList()){
//                for(Organization o:e.getOrganizationList().getOrganizationList()){
//                    for(User u:o.getUserList().getUserList()){
//                        userList.getUserList().add(u);
//                    }
//                }
//            }
//        }
        User user = userList.authenticateUser(username, password);
        if(user!=null){
            Organization inOrganization = null;
            Enterprise inEnterprise = user.getEnterprise();
            CardLayout layout=(CardLayout)rightPanel.getLayout();
            
//            System.out.println(user.getRole());
//            System.out.println(user.getEnterprise().getEnterpriseName());
                
            rightPanel.add("workArea",user.getRole().createWorkArea(rightPanel ,db4o, user, inOrganization, inEnterprise, ecosystem));
            layout.next(rightPanel);    
                //rightPanel.btnLog.setText("Logout");
                
                
//            if(pltAdminBtn.isSelected()){
//                PfAdminWorkArea jPanel = new PfAdminWorkArea(rightPanel);
//                rightPanel.add("PfAdminWorkAreaLogin", jPanel);
//                CardLayout layout1 = (CardLayout)rightPanel.getLayout();
//                layout1.next(rightPanel);
//                
//            }else if(streamerBtn.isSelected()){
//                StreamerWorkArea jPanel = new StreamerWorkArea(rightPanel);
//                rightPanel.add("StreamerWorkAreaLogin", jPanel);
//                CardLayout layout1 = (CardLayout)rightPanel.getLayout();
//                layout1.next(rightPanel);
//                
//            }else if(adsAdminBtn.isSelected()){
//                AdAdminWorkAreaJPanel jPanel = new AdAdminWorkAreaJPanel(rightPanel);
//                rightPanel.add("AdAdminWorkAreaLogin", jPanel);
//                CardLayout layout1= (CardLayout)rightPanel.getLayout();
//                layout1.next(rightPanel);
//                
//            }else if(sponsorBtn.isSelected()){
//                SponsorWorkAreaJPanel jPanel = new SponsorWorkAreaJPanel(rightPanel);
//                rightPanel.add("PfAdminWorkAreaLogin", jPanel);
//                CardLayout layout1 = (CardLayout)rightPanel.getLayout();
//                layout1.next(rightPanel);
//                
//            }else if(user.getUserName().equals("admin")){
//                AdminWorkArea jPanel = new AdminWorkArea(db4o, rightPanel, ecosystem);
//                rightPanel.add("adminWorkAreaLogin", jPanel);
//                CardLayout layout1 = (CardLayout)rightPanel.getLayout();
//                layout1.next(rightPanel);
//                
//            }else{
//                JOptionPane.showMessageDialog(null,"Please select your role");
//            }
            
        }else{
            JOptionPane.showMessageDialog(null,"Password doesn't match with the username");
        }
        
    }//GEN-LAST:event_loginBtnActionPerformed

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        // TODO add your handling code here:
        SignupJPanel signupJPanel = new SignupJPanel(rightPanel);
        rightPanel.add("signupJPanel", signupJPanel);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        layout.next(rightPanel);
 
        
    }//GEN-LAST:event_signupBtnActionPerformed

    private void passwordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JButton signupBtn;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
